# -*- coding: utf-8 -*-
"""Final_Batch 08, Trevesky,  Transfer_Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12lT9sh5H4JtxbzCHiFL_lOQA8P6UF6XJ
"""

from google.colab import drive
drive.mount('/content/drive')

"""Creating Binary Mask"""

import os
import cv2
import json
import numpy as np

# === Paths ===
image_dir = "/content/drive/MyDrive/DL/annotation/Coco-segmentaion/annotation_Coco/images"
json_path = "/content/drive/MyDrive/DL/annotation/Coco-segmentaion/annotation_Coco/result.json"

output_image_dir = "/content/drive/MyDrive/DL/Fin_processed/images"
output_mask_dir = "/content/drive/MyDrive/DL/Fin_processed/masks"

os.makedirs(output_image_dir, exist_ok=True)
os.makedirs(output_mask_dir, exist_ok=True)

# === Load Label Studio JSON ===
with open(json_path, 'r') as f:
    tasks = json.load(f)  # list of tasks

# === Process each task ===
for task in tasks:
    try:
        image_path = task['data']['image'].replace('\\', '/')
        file_name = os.path.basename(image_path)
        full_img_path = os.path.join(image_dir, file_name)

        if not os.path.exists(full_img_path):
            print(f"❌ Image file not found: {full_img_path}")
            continue

        image = cv2.imread(full_img_path)
        if image is None:
            print(f"⚠️ Failed to read image: {file_name}")
            continue

        h, w = image.shape[:2]
        mask = np.zeros((h, w), dtype=np.uint8)

        # Parse polygon annotations
        for ann in task.get("annotations", []):
            for result in ann.get("result", []):
                if result['type'] != 'polygonlabels':
                    continue
                label = result['value']['polygonlabels'][0]
                if label != 'Usable Rooftop Area for Solar Panel Installation':
                    continue

                points = result['value']['points']
                pts = np.array([[int(x * w / 100), int(y * h / 100)] for x, y in points], np.int32)
                pts = pts.reshape((-1, 1, 2))
                cv2.fillPoly(mask, [pts], 255)

        # Save original image
        cv2.imwrite(os.path.join(output_image_dir, file_name), image)

        # Save binary mask
        mask = (mask > 0).astype(np.uint8) * 255
        cv2.imwrite(os.path.join(output_mask_dir, file_name), mask)

    except Exception as e:
        print(f"❌ Error processing {file_name}: {e}")

print("✅ Done: Processed binary masks for usable rooftop areas.")

"""Renaming Images"""

import os
import re
import cv2

# === Input folders ===
input_image_dir = "/content/drive/MyDrive/DL/Fin_processed/images"
input_mask_dir = "/content/drive/MyDrive/DL/Fin_processed/masks"

# === Output folders ===
output_image_dir = "/content/drive/MyDrive/DL/FF_renamed/images"
output_mask_dir = "/content/drive/MyDrive/DL/FF_renamed/masks"

os.makedirs(output_image_dir, exist_ok=True)
os.makedirs(output_mask_dir, exist_ok=True)

# === Extract imageXXX pattern ===
def extract_image_suffix(filename):
    match = re.search(r'(image\d+)', filename)
    return match.group(1) if match else None

image_files = [f for f in os.listdir(input_image_dir) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]
mask_files = [f for f in os.listdir(input_mask_dir) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]

# Create suffix-to-filename maps
image_map = {extract_image_suffix(f): f for f in image_files if extract_image_suffix(f)}
mask_map = {extract_image_suffix(f): f for f in mask_files if extract_image_suffix(f)}

# Common matching keys
common_keys = sorted(set(image_map.keys()) & set(mask_map.keys()), key=lambda x: int(x.replace("image", "")))

for key in common_keys:
    img_path = os.path.join(input_image_dir, image_map[key])
    mask_path = os.path.join(input_mask_dir, mask_map[key])

    image = cv2.imread(img_path)
    mask = cv2.imread(mask_path, cv2.IMREAD_UNCHANGED)  # preserve original format

    if image is None or mask is None:
        print(f"⚠️ Skipped: {key}")
        continue

    # === Construct output filenames ===
    img_out_name = f"{key}.png"
    mask_out_name = f"mask{key.replace('image', '')}.png"

    # === Save ===
    cv2.imwrite(os.path.join(output_image_dir, img_out_name), image)
    cv2.imwrite(os.path.join(output_mask_dir, mask_out_name), mask)

print("✅ All images and masks renamed: imageXXX.png / maskXXX.png")

"""Loading my Dataset"""

import os
import random
import numpy as np
import tensorflow as tf
import glob

SEED = 42
os.environ['PYTHONHASHSEED'] = str(SEED)
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

import os
import glob
import numpy as np

# === Helper: extract index from filenames ===
def extract_index(path, prefix):
    filename = os.path.basename(path)
    number = filename.replace(prefix, '').replace('.png', '')
    return int(number.lstrip('0') or '0')

# === Load and sort paths ===
image_paths = sorted(
    glob.glob("/content/drive/MyDrive/DL/new anno/images/image*.png"),
    key=lambda p: extract_index(p, 'image')
)
mask_paths = sorted(
    glob.glob("/content/drive/MyDrive/DL/new anno/masks/mask*.png"),
    key=lambda p: extract_index(p, 'mask')
)

# === Limit to 236 image–mask pairs ===
image_paths = image_paths[:250]
mask_paths = mask_paths[:250]
print("✅ Loaded:", len(image_paths), "image-mask path pairs.")

# === Fixed test indices (convert to 0-based) ===
fixed_test_numbers = [14,27,25,29,30,31,32,40,66,65,72,84,104,111,116,121,118,131,136,197,184,102]
test_indices = [i - 1 for i in fixed_test_numbers]

# === Remaining indices after removing test ===
all_indices = list(range(236))
remaining_indices = sorted(list(set(all_indices) - set(test_indices)))
np.random.shuffle(remaining_indices)

# === 90/10 split on remaining ===
split_idx = int(0.8 * len(remaining_indices))
train_indices = sorted(remaining_indices[:split_idx])
val_indices = sorted(remaining_indices[split_idx:])

# === Create path lists ===
train_image_paths = [image_paths[i] for i in train_indices]
train_mask_paths  = [mask_paths[i] for i in train_indices]
val_image_paths   = [image_paths[i] for i in val_indices]
val_mask_paths    = [mask_paths[i] for i in val_indices]
test_image_paths  = [image_paths[i] for i in test_indices]
test_mask_paths   = [mask_paths[i] for i in test_indices]

# === Summary ===
print(f"✅ Train: {len(train_image_paths)} samples")
print(f"✅ Valid: {len(val_image_paths)} samples")
print(f"✅ Test : {len(test_image_paths)} samples")

"""Augmentation"""

import tensorflow as tf

def augment(image, mask):
    image = tf.image.convert_image_dtype(image, tf.float32)
    mask = tf.cast(mask, tf.float32)

    # Flips
    if tf.random.uniform(()) > 0.5:
        image = tf.image.flip_left_right(image)
        mask = tf.image.flip_left_right(mask)
    if tf.random.uniform(()) > 0.5:
        image = tf.image.flip_up_down(image)
        mask = tf.image.flip_up_down(mask)

    # Rotation
    if tf.random.uniform(()) > 0.5:
        k = tf.random.uniform((), 0, 4, dtype=tf.int32)
        image = tf.image.rot90(image, k)
        mask = tf.image.rot90(mask, k)

    # Brightness & contrast (mild)
    if tf.random.uniform(()) > 0.5:
        image = tf.image.random_brightness(image, 0.1)
    if tf.random.uniform(()) > 0.5:
        image = tf.image.random_contrast(image, 0.95, 1.05)

    # Light Gaussian noise
    if tf.random.uniform(()) > 0.5:
        noise = tf.random.normal(tf.shape(image), stddev=0.01)
        image = tf.clip_by_value(image + noise, 0.0, 1.0)

    # Zoom-in (safe range)
    if tf.random.uniform(()) > 0.5:
        scale = tf.random.uniform([], 0.85, 1.0)
        crop_size = tf.cast(scale * 256, tf.int32)
        offset = (256 - crop_size) // 2
        image = tf.image.crop_to_bounding_box(image, offset, offset, crop_size, crop_size)
        mask = tf.image.crop_to_bounding_box(mask, offset, offset, crop_size, crop_size)
        image = tf.image.resize(image, [256, 256])
        mask = tf.image.resize(mask, [256, 256], method='nearest')

    # Ensure binary mask
    mask = tf.where(mask > 0.5, 1.0, 0.0)
    return image, mask

# === Use your existing augment() function ===
def augment_numpy(img, mask):
    # Convert NumPy to Tensor
    img = tf.convert_to_tensor(img, dtype=tf.float32)
    mask = tf.convert_to_tensor(mask, dtype=tf.float32)

    # Apply augmentation
    img, mask = augment(img, mask)

    # Convert back to NumPy
    img = img.numpy()
    mask = mask.numpy()
    return img, mask

# === Custom Data Generator ===
def data_generator(image_list, mask_list, batch_size, do_augment=False):
    while True:
        indices = list(range(len(image_list)))
        random.shuffle(indices)
        for i in range(0, len(indices), batch_size):
            batch_images, batch_masks = [], []
            batch_ids = indices[i:i + batch_size]
            for idx in batch_ids:
                img = cv2.imread(image_list[idx])
                img = cv2.resize(img, (256, 256))
                img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB).astype(np.float32) / 255.0

                mask = cv2.imread(mask_list[idx], cv2.IMREAD_GRAYSCALE)
                mask = cv2.resize(mask, (256, 256), interpolation=cv2.INTER_NEAREST)
                mask = (mask > 127).astype(np.float32)
                mask = np.expand_dims(mask, axis=-1)

                if do_augment:
                    img, mask = augment_numpy(img, mask)

                batch_images.append(img)
                batch_masks.append(mask)

            yield np.stack(batch_images), np.stack(batch_masks)

BATCH_SIZE = 8
# === Generators ===
train_dataset = data_generator(train_image_paths, train_mask_paths, BATCH_SIZE, do_augment=True)
val_dataset   = data_generator(val_image_paths, val_mask_paths, BATCH_SIZE, do_augment=False)
test_dataset  = data_generator(test_image_paths, test_mask_paths, BATCH_SIZE, do_augment=False)

# === Steps ===
steps_per_epoch    = len(train_image_paths) // BATCH_SIZE
validation_steps   = len(val_image_paths) // BATCH_SIZE
test_steps         = len(test_image_paths) // BATCH_SIZE

"""Custom loss and Metric"""

def iou_metric(y_true, y_pred):
    y_true = tf.cast(y_true, tf.float32)  # <- Add this line
    y_pred = tf.cast(y_pred > 0.5, tf.float32)
    intersection = tf.reduce_sum(y_true * y_pred)
    union = tf.reduce_sum(y_true) + tf.reduce_sum(y_pred) - intersection
    return intersection / (union + 1e-7)


def dice_loss(y_true, y_pred, smooth=1e-6):
    y_true_f = tf.keras.backend.flatten(y_true)
    y_pred_f = tf.keras.backend.flatten(y_pred)
    intersection = tf.reduce_sum(y_true_f * y_pred_f)
    return 1 - (2. * intersection + smooth) / (
        tf.reduce_sum(y_true_f) + tf.reduce_sum(y_pred_f) + smooth
    )

def combo_loss(y_true, y_pred):
    bce = tf.keras.losses.binary_crossentropy(y_true, y_pred)
    return bce + dice_loss(y_true, y_pred)

"""Load Pretrained Model"""

from tensorflow.keras.models import load_model
from tensorflow.keras import layers
import tensorflow as tf
import numpy as np
import cv2
import matplotlib.pyplot as plt
@tf.keras.utils.register_keras_serializable()
def dice_focal_loss(y_true, y_pred, gamma=2.0, alpha=0.25):
    y_true = tf.cast(y_true, tf.float32)
    y_pred = tf.clip_by_value(tf.cast(y_pred, tf.float32), 1e-7, 1 - 1e-7)

    # Dice part
    intersection = tf.reduce_sum(y_true * y_pred)
    dice = 1 - (2. * intersection + 1e-6) / (tf.reduce_sum(y_true) + tf.reduce_sum(y_pred) + 1e-6)

    # Focal part
    bce = -y_true * tf.math.log(y_pred) * alpha * tf.math.pow(1 - y_pred, gamma) \
          - (1 - y_true) * tf.math.log(1 - y_pred) * (1 - alpha) * tf.math.pow(y_pred, gamma)
    focal = tf.reduce_mean(bce)

    return dice + focal


# === Register previous loss functions (required for loading) ===
@tf.keras.utils.register_keras_serializable()
def dice_loss(y_true, y_pred, smooth=1e-6):
    y_true_f = tf.keras.backend.flatten(tf.cast(y_true, tf.float32))
    y_pred_f = tf.keras.backend.flatten(tf.cast(y_pred, tf.float32))
    intersection = tf.reduce_sum(y_true_f * y_pred_f)
    return 1 - (2. * intersection + smooth) / (tf.reduce_sum(y_true_f) + tf.reduce_sum(y_pred_f) + smooth)

@tf.keras.utils.register_keras_serializable()
def combo_loss(y_true, y_pred):
    bce = tf.keras.losses.binary_crossentropy(y_true, y_pred)
    return bce + dice_loss(y_true, y_pred)

@tf.keras.utils.register_keras_serializable()
def iou_metric(y_true, y_pred):
    y_true = tf.cast(y_true, tf.float32)
    y_pred = tf.cast(y_pred > 0.5, tf.float32)
    intersection = tf.reduce_sum(y_true * y_pred)
    union = tf.reduce_sum(y_true) + tf.reduce_sum(y_pred) - intersection
    return intersection / (union + 1e-7)
@tf.keras.utils.register_keras_serializable()
def combo_tversky_loss(y_true, y_pred):
    bce = tf.keras.losses.binary_crossentropy(y_true, y_pred)
    tv = tversky_loss(y_true, y_pred)
    return bce + tv

@tf.keras.utils.register_keras_serializable()
def tversky_loss(y_true, y_pred, alpha=0.5, beta=0.5, smooth=1e-6):
    y_true = tf.cast(y_true, tf.float32)
    y_pred = tf.clip_by_value(y_pred, 1e-7, 1 - 1e-7)
    tp = tf.reduce_sum(y_true * y_pred)
    fn = tf.reduce_sum(y_true * (1 - y_pred))
    fp = tf.reduce_sum((1 - y_true) * y_pred)
    return 1 - (tp + smooth) / (tp + alpha * fn + beta * fp + smooth)


# === Load Pretrained Model ===
model = load_model(
    '/content/drive/MyDrive/DL/v2_1671final_model.keras',
    custom_objects={
        'combo_loss': combo_loss,
        'dice_loss': dice_loss,
        'iou_metric': iou_metric,
        'tversky_loss': tversky_loss
    }
)

# === Compile with adaptive LR using ReduceLROnPlateau ===
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),  # use float, not schedule
    loss=tversky_loss,
    metrics=['accuracy', iou_metric]
)

# === Callbacks ===
callbacks = [
    tf.keras.callbacks.EarlyStopping(monitor='val_iou_metric', patience=8, mode='max', restore_best_weights=True),
    tf.keras.callbacks.ModelCheckpoint('best_model.keras', monitor='val_iou_metric', mode='max', save_best_only=True),
    tf.keras.callbacks.ReduceLROnPlateau(monitor='val_iou_metric', mode='max', factor=0.5, patience=4, min_lr=1e-6, verbose=1)
]

# === Fit the Model ===
history = model.fit(
    train_dataset,
    validation_data=val_dataset,
    epochs=250,
    steps_per_epoch=steps_per_epoch,
    validation_steps=validation_steps,
    callbacks=callbacks
)

# === Evaluate on Test Set ===
#test_loss, test_accuracy, test_iou = model.evaluate(test_dataset)
#print(f"\n🧪 Test Evaluation:")
#print(f"Test Loss     : {test_loss:.4f}")
#print(f"Test Accuracy : {test_accuracy:.4f}")
#print(f"Test IoU      : {test_iou:.4f}")

"""Predicted mask on test Images"""

import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf

def compute_iou(y_true, y_pred):
    y_true = y_true.astype(np.float32).flatten()
    y_pred = (y_pred > 0.5).astype(np.float32).flatten()
    intersection = np.sum(y_true * y_pred)
    union = np.sum(y_true) + np.sum(y_pred) - intersection
    return intersection / (union + 1e-7)

def color_mask(mask):
    """Convert binary mask to yellow and purple RGB image"""
    colored = np.zeros((*mask.shape, 3), dtype=np.uint8)
    colored[mask == 1] = [255, 255, 0]    # Yellow
    colored[mask == 0] = [128, 0, 128]    # Purple
    return colored

def collect_all_predictions(generator, total_images=21):
    samples = []
    seen = 0

    for images, true_masks in generator:
        preds = model.predict(images)
        for i in range(images.shape[0]):
            if seen >= total_images:
                return samples
            image = images[i]
            true = true_masks[i].squeeze()
            pred = preds[i].squeeze()
            iou = compute_iou(true, pred)
            samples.append({
                "image": image,
                "true_mask": true,
                "pred_mask": (pred > 0.5).astype(np.uint8),
                "iou": iou
            })
            seen += 1
        if seen >= total_images:
            break
    return samples

def show_all_predictions(samples):
    for i, s in enumerate(samples):
        plt.figure(figsize=(12, 4))
        plt.suptitle(f"Test Image {i+1} | IoU: {s['iou']:.4f}")

        plt.subplot(1, 3, 1)
        plt.title("Input Image")
        plt.imshow(s["image"])

        plt.subplot(1, 3, 2)
        plt.title("True Mask")
        plt.imshow(color_mask(s["true_mask"]))

        plt.subplot(1, 3, 3)
        plt.title("Predicted Mask")
        plt.imshow(color_mask(s["pred_mask"]))

        plt.show()

# === Collect and display all 21 predictions ===
samples = collect_all_predictions(test_dataset, total_images=21)
show_all_predictions(samples)

"""Save in PC of Test images"""

import os
import zipfile
import shutil
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

# === Compute IoU ===
def compute_iou(y_true, y_pred):
    y_true = y_true.astype(np.float32).flatten()
    y_pred = (y_pred > 0.5).astype(np.float32).flatten()
    intersection = np.sum(y_true * y_pred)
    union = np.sum(y_true) + np.sum(y_pred) - intersection
    return intersection / (union + 1e-7)

# === Colored binary mask ===
def color_mask(mask):
    colored = np.zeros((*mask.shape, 3), dtype=np.uint8)
    colored[mask == 1] = [255, 255, 0]    # Yellow
    colored[mask == 0] = [128, 0, 128]    # Purple
    return colored

# === Collect predictions from test dataset ===
def collect_test_predictions(generator, total_images=21):
    samples = []
    seen = 0
    for images, true_masks in generator:
        preds = model.predict(images)
        for i in range(images.shape[0]):
            if seen >= total_images:
                return samples
            image = images[i]
            true = true_masks[i].squeeze()
            pred = preds[i].squeeze()
            iou = compute_iou(true, pred)
            samples.append({
                "image": image,
                "true_mask": true,
                "pred_mask": (pred > 0.5).astype(np.uint8),
                "iou": iou
            })
            seen += 1
        if seen >= total_images:
            break
    return samples

# === Save predictions to image files ===
def save_test_predictions(samples, output_dir='test_output_results'):
    os.makedirs(output_dir, exist_ok=True)
    for i, s in enumerate(samples):
        fig, axs = plt.subplots(1, 3, figsize=(12, 4))
        fig.suptitle(f"Test Image {i+1} | IoU: {s['iou']:.4f}", fontsize=14)

        axs[0].imshow(s["image"])
        axs[0].set_title("Input Image")
        axs[0].axis("off")

        axs[1].imshow(color_mask(s["true_mask"]))
        axs[1].set_title("True Mask")
        axs[1].axis("off")

        axs[2].imshow(color_mask(s["pred_mask"]))
        axs[2].set_title("Predicted Mask")
        axs[2].axis("off")

        plt.tight_layout()
        save_path = os.path.join(output_dir, f"test_image_{i+1:02d}.png")
        plt.savefig(save_path)
        plt.close(fig)

# === Zip output folder ===
def zip_output_folder(folder_path='test_output_results', zip_name='test_predicted_results.zip'):
    if os.path.exists(zip_name):
        os.remove(zip_name)
    shutil.make_archive(zip_name.replace('.zip', ''), 'zip', folder_path)
    print(f"✅ ZIP created at: {os.path.abspath(zip_name)}")
    return zip_name

# === Run everything ===
samples = collect_test_predictions(test_dataset, total_images=21)
save_test_predictions(samples)
zip_path = zip_output_folder()

# === Optional (Colab Only): Download via browser ===
try:
    from google.colab import files
    files.download(zip_path)
except:
    print("🖥️  If you're running locally, find your ZIP here:", os.path.abspath(zip_path))

import os
import zipfile
import shutil
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

# === Compute IoU ===
def compute_iou(y_true, y_pred):
    y_true = y_true.astype(np.float32).flatten()
    y_pred = (y_pred > 0.5).astype(np.float32).flatten()
    intersection = np.sum(y_true * y_pred)
    union = np.sum(y_true) + np.sum(y_pred) - intersection
    return intersection / (union + 1e-7)

# === Colored binary mask ===
def color_mask(mask):
    colored = np.zeros((*mask.shape, 3), dtype=np.uint8)
    colored[mask == 1] = [255, 255, 0]    # Yellow
    colored[mask == 0] = [128, 0, 128]    # Purple
    return colored

# === Collect predictions from training dataset ===
def collect_all_predictions(generator, total_images=100):
    samples = []
    seen = 0
    for images, true_masks in generator:
        preds = model.predict(images)
        for i in range(images.shape[0]):
            if seen >= total_images:
                return samples
            image = images[i]
            true = true_masks[i].squeeze()
            pred = preds[i].squeeze()
            iou = compute_iou(true, pred)
            samples.append({
                "image": image,
                "true_mask": true,
                "pred_mask": (pred > 0.5).astype(np.uint8),
                "iou": iou
            })
            seen += 1
        if seen >= total_images:
            break
    return samples

# === Save all predictions to image files ===
def save_all_predictions(samples, output_dir='train_output_results'):
    os.makedirs(output_dir, exist_ok=True)
    for i, s in enumerate(samples):
        fig, axs = plt.subplots(1, 3, figsize=(12, 4))
        fig.suptitle(f"Train Image {i+1} | IoU: {s['iou']:.4f}", fontsize=14)

        axs[0].imshow(s["image"])
        axs[0].set_title("Input Image")
        axs[0].axis("off")

        axs[1].imshow(color_mask(s["true_mask"]))
        axs[1].set_title("True Mask")
        axs[1].axis("off")

        axs[2].imshow(color_mask(s["pred_mask"]))
        axs[2].set_title("Predicted Mask")
        axs[2].axis("off")

        plt.tight_layout()
        save_path = os.path.join(output_dir, f"train_image_{i+1:02d}.png")
        plt.savefig(save_path)
        plt.close(fig)

# === Zip output folder ===
def zip_output_folder(folder_path='train_output_results', zip_name='train_predicted_results.zip'):
    if os.path.exists(zip_name):
        os.remove(zip_name)
    shutil.make_archive(zip_name.replace('.zip', ''), 'zip', folder_path)
    print(f"✅ ZIP created at: {os.path.abspath(zip_name)}")
    return zip_name

# === Run everything ===
samples = collect_all_predictions(train_dataset, total_images=100)
save_all_predictions(samples)
zip_path = zip_output_folder()

# === Optional (Colab Only): Download via browser ===
try:
    from google.colab import files
    files.download(zip_path)
except:
    print("🖥️  If you're running locally, find your ZIP here:", os.path.abspath(zip_path))

"""Plot history"""

import os
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from google.colab import files

def save_and_download_all_plots(history, save_dir="/content/training_plots", dpi=300):
    os.makedirs(save_dir, exist_ok=True)

    # Extract metrics
    acc     = history.history['accuracy']
    val_acc = history.history['val_accuracy']
    loss    = history.history['loss']
    val_loss= history.history['val_loss']
    iou     = history.history['iou_metric']
    val_iou = history.history['val_iou_metric']
    epochs  = range(1, len(acc) + 1)

    # Paths
    loss_path     = os.path.join(save_dir, "loss.png")
    acc_path      = os.path.join(save_dir, "accuracy.png")
    iou_path      = os.path.join(save_dir, "iou.png")
    val_iou_path  = os.path.join(save_dir, "val_iou_metric.png")
    pdf_path      = os.path.join(save_dir, "training_curves.pdf")

    figures = []

    # Plot Loss
    plt.figure(figsize=(6, 4))
    plt.plot(epochs, loss, label='Train Loss')
    plt.plot(epochs, val_loss, label='Val Loss')
    plt.title('Loss over Epochs')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()
    plt.tight_layout()
    plt.savefig(loss_path, dpi=dpi)
    figures.append(plt.gcf())
    plt.close()

    # Plot Accuracy
    plt.figure(figsize=(6, 4))
    plt.plot(epochs, acc, label='Train Accuracy')
    plt.plot(epochs, val_acc, label='Val Accuracy')
    plt.title('Accuracy over Epochs')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.tight_layout()
    plt.savefig(acc_path, dpi=dpi)
    figures.append(plt.gcf())
    plt.close()

    # Plot IoU (train + val together)
    plt.figure(figsize=(6, 4))
    plt.plot(epochs, iou, label='Train IoU')
    plt.plot(epochs, val_iou, label='Val IoU')
    plt.title('IoU over Epochs')
    plt.xlabel('Epochs')
    plt.ylabel('IoU')
    plt.legend()
    plt.tight_layout()
    plt.savefig(iou_path, dpi=dpi)
    figures.append(plt.gcf())
    plt.close()

    # Plot Val IoU only (optional)
    plt.figure(figsize=(6, 4))
    plt.plot(epochs, val_iou, label='Val IoU', color='orange')
    plt.title('Validation IoU over Epochs')
    plt.xlabel('Epochs')
    plt.ylabel('Val IoU')
    plt.legend()
    plt.tight_layout()
    plt.savefig(val_iou_path, dpi=dpi)
    figures.append(plt.gcf())
    plt.close()

    # Combine into a PDF
    with PdfPages(pdf_path) as pdf:
        for fig in figures:
            pdf.savefig(fig)

    # Download all files
    print("⬇️ Downloading plots to your PC...")
    files.download(loss_path)
    files.download(acc_path)
    files.download(iou_path)
    files.download(val_iou_path)
    files.download(pdf_path)

# ✅ Call this after training
save_and_download_all_plots(history)

plt.savefig("val_loss_vs_epochs.png", dpi=300)

model.save('/content/drive/MyDrive/DL/my_model_v6.h5')

# Save the model in .keras format
model.save('final_result_minev1.keras')

# Download the file
from google.colab import files
files.download('final_result_minev1.keras')

import os
import numpy as np
import pandas as pd
import shutil
import matplotlib.pyplot as plt
from PIL import Image
import tensorflow as tf
from tensorflow.keras.preprocessing.image import load_img, img_to_array

# === Constants ===
IMAGE_FOLDER = '/content/drive/MyDrive/DL/new anno/images'
MODEL_PATH = '/content/drive/MyDrive/DL/my_model_v6.h5'
OUTPUT_FOLDER = 'overlay_results_yellow_only'
ZIP_FILENAME = 'overlay_results_yellow_only.zip'
CSV_FILENAME = 'solar_generation_estimates.csv'

SOLAR_IRRADIANCE = 4.5     # kWh/m²/day
EFFICIENCY = 0.18          # 18%
PIXEL_AREA_M2 = 0.0625  # m² per pixel (based on Google Earth scale)

IMAGE_SIZE = (256, 256)

# === Load model ===
model = tf.keras.models.load_model(MODEL_PATH, compile=False)

# === Prepare output directory ===
if os.path.exists(OUTPUT_FOLDER):
    shutil.rmtree(OUTPUT_FOLDER)
os.makedirs(OUTPUT_FOLDER)

# === Process images ===
results = []

for filename in sorted(os.listdir(IMAGE_FOLDER)):
    if not filename.lower().endswith(('.png', '.jpg', '.jpeg')):
        continue

    img_path = os.path.join(IMAGE_FOLDER, filename)

    # Load and preprocess image
    img = load_img(img_path, target_size=IMAGE_SIZE)
    img_array = img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    # Predict mask
    pred = model.predict(img_array)[0].squeeze()
    binary_mask = (pred > 0.5).astype(np.uint8)

    # Compute area and energy
    usable_pixels = np.sum(binary_mask)
    usable_area_m2 = usable_pixels * PIXEL_AREA_M2
    daily_kwh = usable_area_m2 * SOLAR_IRRADIANCE * EFFICIENCY
    monthly_kwh = daily_kwh * 30
    yearly_kwh = daily_kwh * 365

    # Overlay yellow rooftop area
    original = np.array(img.resize(IMAGE_SIZE)).astype(np.uint8)
    overlay = original.copy()
    overlay[binary_mask == 1] = (0.6 * original[binary_mask == 1] + 0.4 * np.array([255, 255, 0])).astype(np.uint8)

    # Plot and annotate
    fig, ax = plt.subplots(figsize=(6, 6))
    ax.imshow(overlay)
    ax.set_title(f"{filename}", fontsize=10)
    ax.axis("off")

    text = f"Usable Area: {usable_area_m2:.2f} m²\nEst. Daily Gen: {daily_kwh:.2f} kWh"
    ax.text(5, 20, text, fontsize=10, color='black', backgroundcolor='white', alpha=0.7)

    # Save annotated image
    save_path = os.path.join(OUTPUT_FOLDER, filename)
    plt.tight_layout()
    plt.savefig(save_path, bbox_inches='tight')
    plt.close()

    # Save data
    results.append({
        "Image": filename,
        "Usable Area (m²)": round(usable_area_m2, 2),
        "Daily Generation (kWh)": round(daily_kwh, 2),
        "Monthly Generation (kWh)": round(monthly_kwh, 2),
        "Yearly Generation (kWh)": round(yearly_kwh, 2)
    })

# === Save CSV separately ===
csv_path = os.path.join(OUTPUT_FOLDER, CSV_FILENAME)
df = pd.DataFrame(results)
df.to_csv(csv_path, index=False)

# === Zip the folder ===
shutil.make_archive(OUTPUT_FOLDER, 'zip', OUTPUT_FOLDER)
print(f"✅ ZIP saved: {os.path.abspath(ZIP_FILENAME)}")
print(f"✅ CSV saved: {os.path.abspath(csv_path)}")

# === Optional download (if in Colab) ===
try:
    from google.colab import files
    files.download(csv_path)                         # CSV file
    files.download(f"{OUTPUT_FOLDER}.zip")           # ZIP file
except:
    print("🖥️ Download manually from paths above.")